# Đặng Minh Ngôn - 2370341

In [28]:
import math
import numpy as np
import pandas as pd

In [2]:
train = pd.read_csv("../data/train.csv")

In [3]:
print(train)

   ID  Age  CreditScore  Education RiskLevel
0   1   35          720       16.0      Low 
1   2   28          650       14.0      High
2   3   45          750        NaN      Low 
3   4   31          600       12.0      High
4   5   52          780       18.0      Low 
5   6   29          630       14.0      High
6   7   42          710       16.0      Low 
7   8   33          640       12.0      High


In [16]:
def entropy(labels):
    total = len(labels)
    if total == 0:
        return 0
        
    counts = labels.value_counts()
    # print(total, counts)

    return -sum((count / total) * math.log2(count / total) for count in counts)
    

# Question 1

In [17]:
# Full dataset entropy
full_entropy = entropy(train["RiskLevel"])

In [18]:
full_entropy

1.0

In [19]:
# Split the data where CreditScore <=650
left_split = train[train['CreditScore'] <= 650]
right_split = train[train['CreditScore'] > 650]

In [20]:
print(left_split, right_split)

   ID  Age  CreditScore  Education RiskLevel
1   2   28          650       14.0      High
3   4   31          600       12.0      High
5   6   29          630       14.0      High
7   8   33          640       12.0      High    ID  Age  CreditScore  Education RiskLevel
0   1   35          720       16.0      Low 
2   3   45          750        NaN      Low 
4   5   52          780       18.0      Low 
6   7   42          710       16.0      Low 


In [21]:
weighted_entropy = (len(left_split) / len(train)) * entropy(left_split['RiskLevel']) + \
                   (len(right_split) / len(train)) * entropy(right_split['RiskLevel'])

In [22]:
print(weighted_entropy)

-0.0


In [23]:
info_gain = full_entropy - weighted_entropy

In [24]:
print(f"Full Entropy: {full_entropy:.4f}")
print(f"Left Split Entropy (<= 650): {entropy(left_split['RiskLevel']):.4f}")
print(f"Right Split Entropy (> 650): {entropy(right_split['RiskLevel']):.4f}")
print(f"Information Gain for splitting at CreditScore = 650: {info_gain:.4f}")

Full Entropy: 1.0000
Left Split Entropy (<= 650): -0.0000
Right Split Entropy (> 650): -0.0000
Information Gain for splitting at CreditScore = 650: 1.0000


### Because Information Gain is = 1 so this is the best node to split

# Question 2

In [29]:
# All credit scores and corresponding ages
ages = train['Age'].values
credit_scores = train['CreditScore'].values

In [30]:
print(ages)

[35 28 45 31 52 29 42 33]


In [36]:
# Total variance before split
mean_total = np.mean(credit_scores)
var_total = np.mean((credit_scores - mean_total) ** 2)

In [37]:
print(var_total)

3575.0


In [32]:
# Split by Age <= 35 and Age > 35
left = credit_scores[ages <= 35]
right = credit_scores[ages > 35]

In [38]:
print(left)
print(right)

[720 650 600 630 640]
[750 780 710]


In [33]:
var_left = np.mean((left - np.mean(left)) ** 2)
var_right = np.mean((right - np.mean(right)) ** 2)

In [39]:
print(var_left)
print(var_right)

1576.0
822.2222222222222


In [41]:
weighted_var_after = (len(left) / len(credit_scores)) * var_left + \
                     (len(right) / len(credit_scores)) * var_right

In [42]:
weighted_var_after

1293.3333333333333

In [40]:
var_reduction = var_total - weighted_var_after
var_reduction

2281.666666666667